### ISSUE TITLE
Droping failed Stream results in a panic

### ISSUE THREAD

**Issue by futpib** [jnqnfe/pulse-binding-rust#11]
When trying to delete a failed stream (from a `HashMap`) I get this error: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PAErr(-15)', libcore/result.rs:1009:5
```
<details>
 <summary>Stack trace</summary>
<p>

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
             at /build/rust/src/rustc-1.30.1-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /build/rust/src/rustc-1.30.1-src/src/libcore/result.rs:808
  10: <libpulse_binding::stream::Stream as core::ops::drop::Drop>::drop
             at /home/futpib/.cargo/registry/src/github.com-1ecc6299db9ec823/libpulse-binding-2.3.0/src/stream.rs:1613
  11: core::ptr::drop_in_place
             at /build/rust/src/rustc-1.30.1-src/src/libcore/ptr.rs:59
  12: core::ptr::drop_in_place
             at /build/rust/src/rustc-1.30.1-src/src/libcore/ptr.rs:59
  13: core::ptr::drop_in_place
             at /build/rust/src/rustc-1.30.1-src/src/libcore/ptr.rs:59
  14: core::ptr::drop_in_place
             at /build/rust/src/rustc-1.30.1-src/src/libcore/ptr.rs:59
  15: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
             at /build/rust/src/rustc-1.30.1-src/src/liballoc/rc.rs:835
  16: core::ptr::drop_in_place
             at /build/rust/src/rustc-1.30.1-src/src/libcore/ptr.rs:59
  17: <std::collections::hash::map::HashMap<K, V, S>>::retain
             at /build/rust/src/rustc-1.30.1-src/src/libstd/collections/hash/map.rs:1471
  18: papeaks::main
             at src/main.rs:181
  19: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.30.1-src/src/libstd/rt.rs:74
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: std::rt::lang_start
             at /build/rust/src/rustc-1.30.1-src/src/libstd/rt.rs:74
  24: main
  25: __libc_start_main
  26: _start
```

</p>
</details>

I think `Drop` implementation should not call `disconnect` if the stream is not in `PA_CONTEXT_READY` as PulseAudio's `pa_stream_disconnect` returns `PA_ERR_BADSTATE` which looks like the reason behind `PAErr(-15)`. Alternatively, it may ignore `PAErr(-15)`.

https://github.com/jnqnfe/pulse-binding-rust/blob/012e15c673916ce37218729c49f6611ec580b970/pulse-binding/src/stream.rs#L1611-L1617

https://github.com/jnqnfe/pulse-binding-rust/blob/012e15c673916ce37218729c49f6611ec580b970/pulse-binding/src/stream.rs#L864-L869

**Comment by jnqnfe** [comment]
Thanks for reporting, and thanks for the patch. I've fixed it a slightly different way though, I've just changed it to no longer attempt to unwrap the result value at all. I feel that there was no real need, I guess I just naively never expected it to actually fail in any real situation of drop being called on a `Stream` object when I wrote that.

So should be fixed for you in the just published v2.4 :)
